#!/usr/bin/env python3
"""
build_demo.py — assemble demo/index.html as a TRUE single, offline file.

The demo is NOT a hand-maintained second copy of the module. It is generated by
inlining the CANONICAL module files (modules/hand-drawn.{css,svg.html,js}) plus
the vendored libraries (demo/vendor/*) into a demo shell. This guarantees the
single-file demo can never drift from the reusable module — the whole point of
the Style Engine's module architecture.

Run:  python scripts/build_demo.py
Out:  demo/index.html
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MOD = ROOT / "modules"
VENDOR = ROOT / "demo" / "vendor"
OUT = ROOT / "demo" / "index.html"


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


module_css = read(MOD / "hand-drawn.css")
svg_defs = read(MOD / "hand-drawn.svg.html")
module_js = read(MOD / "hand-drawn.js")
rough_js = read(VENDOR / "rough.min.js")
roughnote_js = read(VENDOR / "rough-notation.iife.js")

# --- Demo-only chrome. NOTE: layout values (grid gaps, panel width) are NOT
# --- effect magnitudes, so they are plain CSS. Every EFFECT magnitude still
# --- comes only from a --hd-* dial (enforced in the module CSS above). --------
DEMO_CSS = r"""
/* ---------- demo chrome (layout only; no effect magnitudes here) ---------- */
* { box-sizing: border-box; }
body { margin: 0; }
.wrap { max-width: 1180px; margin: 0 auto; padding: 2rem 1.25rem 6rem; }
h1.title { font-size: clamp(2.4rem, 6vw, 4rem); margin: .2em 0 .1em; line-height: 1; }
.tagline { max-width: 60ch; opacity: .8; }
section.demo { margin: 3.2rem 0; }
section.demo > h2 { font-size: 1.6rem; margin: 0 0 .2em; }
.demo__label { font-family: "Caveat","Shantell Sans",cursive; font-size: 1.3rem; color: var(--hd-accent); }
.demo__note { font-size: .9rem; opacity: .7; max-width: 62ch; margin: .2rem 0 1.1rem; }
.grid { display: grid; gap: 1.1rem; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); }
.chip { background: #fff; border: 1px solid var(--hd-ink); padding: .8rem 1rem; }
.sample-fill { background: var(--hd-accent); color: var(--hd-paper); padding: 1.5rem; font-weight: 600; }
canvas { max-width: 100%; height: auto; background: transparent; }

/* control panel */
.panel { position: fixed; top: 0; right: 0; width: 300px; height: 100vh; overflow-y: auto;
         background: rgba(255,255,255,.92); border-left: 2px solid var(--hd-ink);
         padding: 1.1rem 1.1rem 3rem; z-index: 10000; backdrop-filter: blur(2px); }
.panel h3 { margin: .2rem 0 .1rem; font-size: 1.05rem; }
.panel .sub { font-size: .78rem; opacity: .65; margin: 0 0 1rem; }
.dial { margin: .55rem 0 .95rem; }
.dial label { display: flex; justify-content: space-between; font-size: .82rem; font-weight: 600; }
.dial output { font-variant-numeric: tabular-nums; opacity: .7; }
.dial input[type=range] { width: 100%; margin-top: .25rem; accent-color: var(--hd-accent); }
.macro { border: 2px dashed var(--hd-accent); padding: .7rem .8rem; border-radius: 8px; margin-bottom: 1rem; background: rgba(200,69,47,.06); }
.macro label { color: var(--hd-accent); }
.wrap { padding-right: 320px; }
@media (max-width: 820px) {
  .panel { position: static; width: auto; height: auto; border-left: none; border-bottom: 2px solid var(--hd-ink); }
  .wrap { padding-right: 1.25rem; }
}
.btn { font: inherit; border: 1px solid var(--hd-ink); background: var(--hd-paper); padding: .4rem .8rem; cursor: pointer; }
.rmnote { font-size: .78rem; opacity: .7; border-top: 1px dashed var(--hd-ink); padding-top: .7rem; margin-top: 1rem; }
"""

# The seven dials + the macro. label, var, min, max, step, default.
DIALS = [
    ("Wobble", "--hd-wobble", 0, 100, 55),
    ("Grain", "--hd-grain", 0, 100, 12),
    ("Rotation (scatter)", "--hd-rotation", 0, 100, 45),
    ("Boil speed", "--hd-boil-speed", 0, 100, 50),
    ("Sketchiness", "--hd-sketchiness", 0, 100, 50),
    ("Line weight", "--hd-line-weight", 0, 100, 50),
    ("Overshoot", "--hd-overshoot", 0, 100, 45),
]


def dial_html(label, var, lo, hi, val):
    return (
        f'<div class="dial"><label>{label}<output id="out{var}">{val}</output></label>'
        f'<input type="range" min="{lo}" max="{hi}" value="{val}" '
        f'oninput="setDial(\'{var}\', this.value)"></div>'
    )


dials_markup = "\n".join(dial_html(*d) for d in DIALS)

PANEL = f"""
<aside class="panel" aria-label="Style Engine control panel">
  <h3>Style Engine · dials</h3>
  <p class="sub">Every slider writes a <code>--hd-*</code> CSS variable 0–100. This panel is the seed of the future macro UI.</p>

  <div class="macro">
    <div class="dial"><label>MACRO · Hand-Made-ness<output id="outmacro">50</output></label>
    <input type="range" min="0" max="100" value="50" oninput="setMacro(this.value)"></div>
    <p class="sub" style="margin:0">One dial → many params (wobble, rotation, sketchiness, boil, grain), exactly like an Ableton rack macro.</p>
  </div>

  {dials_markup}

  <p class="rmnote" id="rmnote">Motion respects <code>prefers-reduced-motion</code>. Toggle it in your OS to see boil &amp; self-draw freeze.</p>
</aside>
"""

# --------------------------- demo body sections --------------------------- #
BODY = f"""
{PANEL}
<div class="wrap">
  <header>
    <h1 class="title hd-hand">The Hand-Drawn Module</h1>
    <p class="tagline hd-body">Style Engine · Module 1. Every effect below is driven by a
    <strong>0–100 dial</strong> (<code>--hd-*</code>). Drag the sliders on the right — nothing here
    is hard-coded. A future macro layer will drive all of these dials at once.</p>
  </header>

  <section class="demo" id="s-wobble">
    <span class="demo__label">01 · wobbly containers</span>
    <h2 class="hd-body">border-radius that breathes</h2>
    <p class="demo__note">Each box interpolates 8 seeded radii toward the classic
    <code>255px 15px 225px 15px / 15px 225px 15px 255px</code> by the Wobble dial. No two identical.</p>
    <div class="grid">
      <div class="hd-box hd-body"><strong>Ticket #1</strong><br>A wobbly ink container.</div>
      <div class="hd-box hd-body" style="--hdr1:180;--hdr2:30;--hdr3:255;--hdr4:22;--hdr5:40;--hdr6:200;--hdr7:26;--hdr8:210;"><strong>Ticket #2</strong><br>Different seed set.</div>
      <div class="hd-box hd-body" style="--hdr1:60;--hdr2:200;--hdr3:90;--hdr4:175;--hdr5:210;--hdr6:55;--hdr7:190;--hdr8:70;"><strong>Ticket #3</strong><br>Different again.</div>
      <div class="hd-box hd-body"><strong>Ticket #4</strong><br>nth-of-type varies it.</div>
    </div>
  </section>

  <section class="demo" id="s-scatter">
    <span class="demo__label">02 · scatter</span>
    <h2 class="hd-body">prime-cadence rotation (3n / 5n / 7n)</h2>
    <p class="demo__note">Rotations step on primes so they never land on a grid; magnitude ±2–5° from the Rotation dial.</p>
    <div class="grid hd-scatter">
      {''.join(f'<div class="chip hd-body">tag {i+1}</div>' for i in range(12))}
    </div>
  </section>

  <section class="demo" id="s-roughen">
    <span class="demo__label">03 · roughen filter</span>
    <h2 class="hd-body">feTurbulence + feDisplacementMap</h2>
    <p class="demo__note">Displacement <code>scale</code> is an SVG attribute CSS can't set — the JS binder writes it from the Sketchiness dial.</p>
    <div class="grid">
      <div class="sample-fill hd-roughen">roughened block — edges displaced</div>
      <div class="hd-box hd-roughen hd-body">roughen on a wobbly box, stacked</div>
    </div>
  </section>

  <section class="demo" id="s-boil">
    <span class="demo__label">04 · boil animation</span>
    <h2 class="hd-body">discrete baseFrequency stepping</h2>
    <p class="demo__note"><code>calcMode="discrete"</code> is mandatory — it jumps between frames like redrawing by hand. Boil-speed dial writes <code>dur</code>. Frozen under reduced-motion.</p>
    <div class="grid">
      <div class="sample-fill hd-boil">boiling block</div>
      <h2 class="hd-hand hd-boil" style="font-size:2.4rem;color:var(--hd-accent2)">Boiling headline</h2>
    </div>
  </section>

  <section class="demo" id="s-grain">
    <span class="demo__label">05 · grain</span>
    <h2 class="hd-body">fractalNoise paper overlay</h2>
    <p class="demo__note">A fixed full-page grain overlay at 5–15% opacity (Grain dial), multiply-blended over cream paper. Turn Grain up to see it bite.</p>
    <div class="sample-fill hd-body" style="color:var(--hd-paper)">The grain sits above everything as a multiply overlay. Raise the Grain dial.</div>
  </section>

  <section class="demo" id="s-draw">
    <span class="demo__label">06 · self-drawing lines</span>
    <h2 class="hd-body">stroke-dashoffset + getTotalLength()</h2>
    <p class="demo__note">Path length measured with <code>getTotalLength()</code>; the line draws itself. Duration from the Boil-speed dial. Instant under reduced-motion.</p>
    <svg viewBox="0 0 600 120" width="100%" height="120" aria-hidden="true">
      <path class="hd-draw-path" d="M10,90 C120,10 220,140 320,60 S520,10 590,80"/>
    </svg>
    <button class="btn" onclick="StyleEngine.drawLines('.hd-draw-path')">▶ replay draw</button>
  </section>

  <section class="demo" id="s-rough">
    <span class="demo__label">07 · Rough.js shapes</span>
    <h2 class="hd-body">seeded sketchy shapes</h2>
    <p class="demo__note">Rough.js with <code>roughness</code> from the Sketchiness dial, <code>bowing</code>, and a STABLE-per-element seed (stable on reflow, different between shapes). Re-render on dial change.</p>
    <canvas id="roughcanvas" width="1000" height="260"></canvas>
  </section>

  <section class="demo" id="s-note">
    <span class="demo__label">08 · rough-notation</span>
    <h2 class="hd-body">annotations, used <span id="note-underline">sparingly</span></h2>
    <p class="demo__note hd-body">Reserve 3–5 per page for the words that matter most: a
    <span id="note-circle">deadline</span>, a <span id="note-highlight">key number</span>, a
    <span id="note-box">warning</span>. Over-use and the eye stops trusting them.</p>
    <button class="btn" onclick="runNotations()">▶ replay annotations</button>
  </section>

  <section class="demo" id="s-riso">
    <span class="demo__label">09 · risograph poster (composed)</span>
    <h2 class="hd-body">flat inks · multiply · misregistration · halftone</h2>
    <p class="demo__note">2–3 flat inks, each on a multiply layer, offset 1–3px (Sketchiness dial) so overlaps mix and edges misregister. Halftone dot grid underneath.</p>
    <div class="hd-riso" style="position:relative;height:420px;border:1px solid var(--hd-ink);overflow:hidden;background:var(--hd-paper)">
      <div class="hd-halftone" style="position:absolute;inset:0;opacity:.25"></div>
      <div class="hd-riso__layer hd-riso__layer--yellow" style="display:flex;align-items:center;justify-content:center">
        <div style="font:800 clamp(3rem,12vw,7rem)/0.9 'Caveat',cursive;text-align:center">NIGHT<br>PRESS</div>
      </div>
      <div class="hd-riso__layer hd-riso__layer--blue" style="display:flex;align-items:center;justify-content:center">
        <div style="font:800 clamp(3rem,12vw,7rem)/0.9 'Caveat',cursive;text-align:center">NIGHT<br>PRESS</div>
      </div>
      <div class="hd-riso__layer hd-riso__layer--red" style="display:flex;align-items:flex-end;justify-content:center;padding-bottom:1.5rem">
        <div class="hd-body" style="font-weight:700;letter-spacing:.3em">RISO · ZINE · FAIR — SAT 8PM</div>
      </div>
    </div>
  </section>

  <footer class="hd-body" style="opacity:.6;font-size:.85rem;border-top:1px dashed var(--hd-ink);padding-top:1rem">
    Style Engine · Module 1 · Hand-Drawn. Built to prove the dial architecture. Next modules
    (glitch <code>--gl-*</code>, text-motion <code>--tm-*</code>, media-decay <code>--md-*</code>) reuse the same 0–100 convention.
  </footer>
</div>
"""

# --------------------------- demo-only JS --------------------------- #
DEMO_JS = r"""
// setDial proxies to the module's public API and updates the readout.
function setDial(name, value) {
  StyleEngine.setDial(name, value);
  var out = document.getElementById('out' + name);
  if (out) out.textContent = value;
  renderRough();
}

// MACRO: one 0-100 input mapped onto many dials (the future macro layer, in miniature).
// Each mapping is (dialVar, curveFn) so a macro can be non-linear per target.
var MACRO_MAP = [
  ['--hd-wobble',      function (m) { return Math.round(m); }],
  ['--hd-rotation',    function (m) { return Math.round(m * 0.9); }],
  ['--hd-sketchiness', function (m) { return Math.round(m); }],
  ['--hd-boil-speed',  function (m) { return Math.round(m * 0.8); }],
  ['--hd-grain',       function (m) { return Math.round(m * 0.28); }],
  ['--hd-line-weight', function (m) { return Math.round(m); }],
  ['--hd-overshoot',   function (m) { return Math.round(m); }]
];
function setMacro(m) {
  m = parseFloat(m);
  document.getElementById('outmacro').textContent = Math.round(m);
  MACRO_MAP.forEach(function (pair) {
    var v = pair[1](m);
    StyleEngine.setDial(pair[0], v);
    // reflect on the individual slider + readout so users SEE one dial move many
    var slider = document.querySelector('input[oninput*="' + pair[0] + '"]');
    if (slider) slider.value = v;
    var out = document.getElementById('out' + pair[0]);
    if (out) out.textContent = v;
  });
  renderRough();
}

// Rough.js: seeded shapes, roughness from the sketchiness dial. Seeds are
// STABLE per shape (index-based) so shapes don't twitch, but DIFFER between shapes.
function renderRough() {
  var cv = document.getElementById('roughcanvas');
  if (!cv || typeof rough === 'undefined') return;
  var ctx = cv.getContext('2d');
  ctx.clearRect(0, 0, cv.width, cv.height);
  var rc = rough.canvas(cv);
  var sketch = parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--hd-sketchiness')) || 0;
  var roughness = 1 + (sketch / 100) * 1.8;   // dial 0-100 -> roughness 1.0-2.8
  var bowing = 0.5 + (sketch / 100) * 2;
  var ink = getComputedStyle(document.documentElement).getPropertyValue('--hd-ink').trim();
  var red = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent').trim();
  var blue = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent2').trim();
  var opt = function (i, stroke, fill) {
    return { roughness: roughness, bowing: bowing, seed: 1000 + i * 137,
             stroke: stroke, strokeWidth: 2, fill: fill, fillStyle: 'hachure', fillWeight: 1.5, hachureGap: 6 };
  };
  rc.rectangle(30, 30, 200, 190, opt(1, ink, red));
  rc.circle(360, 130, 180, opt(2, ink, blue));
  rc.ellipse(620, 130, 240, 150, opt(3, red, null));
  rc.line(770, 30, 970, 220, opt(4, blue));
  rc.path('M780,210 C820,120 900,120 950,40', opt(5, ink, null));
}

// rough-notation: 3-5 annotations MAX. Skip animation under reduced motion.
var _annotations = [];
function runNotations() {
  if (typeof RoughNotation === 'undefined') return;
  var reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  var red = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent').trim();
  var blue = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent2').trim();
  var yellow = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent3').trim();
  _annotations.forEach(function (a) { a.hide(); });
  var dur = reduce ? 0 : 800;
  _annotations = [
    RoughNotation.annotate(document.getElementById('note-underline'), { type: 'underline', color: red, animationDuration: dur }),
    RoughNotation.annotate(document.getElementById('note-circle'), { type: 'circle', color: blue, padding: 6, animationDuration: dur }),
    RoughNotation.annotate(document.getElementById('note-highlight'), { type: 'highlight', color: yellow, animationDuration: dur }),
    RoughNotation.annotate(document.getElementById('note-box'), { type: 'box', color: red, animationDuration: dur })
  ];
  var group = RoughNotation.annotationGroup(_annotations);
  group.show();
}

document.addEventListener('DOMContentLoaded', function () {
  renderRough();
  runNotations();
});
"""

HTML = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Style Engine · Module 1 · Hand-Drawn — live demo</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%23faf6ef'/%3E%3Cpath d='M15,70 C35,20 65,90 88,30' stroke='%231a1a17' stroke-width='9' fill='none' stroke-linecap='round'/%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500;700&family=Inter:wght@400;600;800&family=Shantell+Sans:wght@500;700&display=swap" rel="stylesheet">
<style>
/* ===== CANONICAL MODULE CSS (inlined verbatim from modules/hand-drawn.css) ===== */
{module_css}
/* ===== demo chrome ===== */
{DEMO_CSS}
</style>
</head>
<body class="hd-page hd-body">
<!-- ===== CANONICAL SVG FILTER DEFS (inlined from modules/hand-drawn.svg.html) ===== -->
{svg_defs}
<!-- full-page grain overlay -->
<svg class="hd-grain-overlay" aria-hidden="true"><rect width="100%" height="100%" filter="url(#hd-grain)"/></svg>

{BODY}

<!-- ===== vendored libraries (inlined) ===== -->
<script>/* Rough.js v4.6.6 (MIT) */ {rough_js}</script>
<script>/* rough-notation v0.2.1 (MIT) */ {roughnote_js}</script>
<!-- ===== CANONICAL MODULE BINDER (inlined verbatim from modules/hand-drawn.js) ===== -->
<script>{module_js}</script>
<!-- ===== demo controls ===== -->
<script>{DEMO_JS}</script>
</body>
</html>
"""

OUT.write_text(HTML, encoding="utf-8")
print(f"wrote {OUT} ({len(HTML):,} bytes)")
