#!/usr/bin/env python3
"""
build_demo.py — assemble demo/index.html as a TRUE single, offline file.

The demo is NOT a hand-maintained second copy of the module. It is generated by
inlining the CANONICAL module files (modules/*.{css,svg.html,js}) plus
the vendored libraries (demo/vendor/*) into a demo shell. This guarantees the
single-file demo can never drift from the reusable modules — the whole point of
the Style Engine's module architecture.

Run:  python scripts/build_demo.py
Out:  demo/index.html
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MOD = ROOT / "modules"
VENDOR = ROOT / "demo" / "vendor"
OUT = ROOT / "demo" / "index.html"


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


# ---- Read ALL module files ------------------------------------------------- #
hd_css = read(MOD / "hand-drawn.css")
hd_svg = read(MOD / "hand-drawn.svg.html")
hd_js = read(MOD / "hand-drawn.js")

gl_css = read(MOD / "glitch.css")
gl_svg = read(MOD / "glitch.svg.html")
gl_js = read(MOD / "glitch.js")

tm_css = read(MOD / "text-motion.css")
tm_js = read(MOD / "text-motion.js")

md_css = read(MOD / "media-decay.css")
md_svg = read(MOD / "media-decay.svg.html")
md_js = read(MOD / "media-decay.js")

macro_js = read(MOD / "macro.js")

rough_js = read(VENDOR / "rough.min.js")
roughnote_js = read(VENDOR / "rough-notation.iife.js")

# ---- Read vendored font files and base64-encode for inline @font-face ---- #
import base64

FONTS = VENDOR / "fonts"

def font_b64(name: str) -> str:
    return base64.b64encode((FONTS / name).read_bytes()).decode("ascii")

caveat_latin_b64 = font_b64("caveat-latin.woff2")
caveat_latin_ext_b64 = font_b64("caveat-latin-ext.woff2")
inter_latin_b64 = font_b64("inter-latin.woff2")
inter_latin_ext_b64 = font_b64("inter-latin-ext.woff2")
shantell_latin_b64 = font_b64("shantell-sans-latin.woff2")
shantell_latin_ext_b64 = font_b64("shantell-sans-latin-ext.woff2")

FONT_FACE_CSS = f"""
@font-face {{
  font-family: 'Caveat';
  font-style: normal;
  font-weight: 400 700;
  font-display: swap;
  src: url(data:font/woff2;base64,{caveat_latin_ext_b64}) format('woff2');
  unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
}}
@font-face {{
  font-family: 'Caveat';
  font-style: normal;
  font-weight: 400 700;
  font-display: swap;
  src: url(data:font/woff2;base64,{caveat_latin_b64}) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}}
@font-face {{
  font-family: 'Inter';
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url(data:font/woff2;base64,{inter_latin_ext_b64}) format('woff2');
  unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
}}
@font-face {{
  font-family: 'Inter';
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url(data:font/woff2;base64,{inter_latin_b64}) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}}
@font-face {{
  font-family: 'Shantell Sans';
  font-style: normal;
  font-weight: 300 800;
  font-display: swap;
  src: url(data:font/woff2;base64,{shantell_latin_ext_b64}) format('woff2');
  unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
}}
@font-face {{
  font-family: 'Shantell Sans';
  font-style: normal;
  font-weight: 300 800;
  font-display: swap;
  src: url(data:font/woff2;base64,{shantell_latin_b64}) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}}
"""

# --- Demo-only chrome. NOTE: layout values (grid gaps, panel width) are NOT
# --- effect magnitudes, so they are plain CSS. Every EFFECT magnitude still
# --- comes only from a --xx-* dial (enforced in the module CSS above). --------
DEMO_CSS = r"""
/* ---------- demo chrome (layout only; no effect magnitudes here) ---------- */
* { box-sizing: border-box; }
body { margin: 0; }
.wrap { max-width: 1180px; margin: 0 auto; padding: 2rem 1.25rem 6rem; }
h1.title { font-size: clamp(2.4rem, 6vw, 4rem); margin: .2em 0 .1em; line-height: 1; }
.tagline { max-width: 60ch; opacity: .8; }
section.demo { margin: 3.2rem 0; }
section.demo > h2 { font-size: 1.6rem; margin: 0 0 .2em; }
.demo__label { font-family: "Caveat","Shantell Sans",cursive; font-size: 1.3rem; color: var(--hd-accent); }
.demo__note { font-size: .9rem; opacity: .7; max-width: 62ch; margin: .2rem 0 1.1rem; }
.grid { display: grid; gap: 1.1rem; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); }
.chip { background: #fff; border: 1px solid var(--hd-ink); padding: .8rem 1rem; }
.sample-fill { background: var(--hd-accent); color: var(--hd-paper); padding: 1.5rem; font-weight: 600; }
canvas { max-width: 100%; height: auto; background: transparent; }

/* control panel */
.panel { position: fixed; top: 0; right: 0; width: 300px; height: 100vh; overflow-y: auto;
         background: rgba(255,255,255,.92); border-left: 2px solid var(--hd-ink);
         padding: 1.1rem 1.1rem 3rem; z-index: 10000;
         -webkit-backdrop-filter: blur(2px); backdrop-filter: blur(2px); }
.panel h3 { margin: .2rem 0 .1rem; font-size: 1.05rem; }
.panel .sub { font-size: .78rem; opacity: .65; margin: 0 0 1rem; }
.dial { margin: .55rem 0 .95rem; }
.dial label { display: flex; justify-content: space-between; font-size: .82rem; font-weight: 600; }
.dial output { font-variant-numeric: tabular-nums; opacity: .7; }
.dial input[type=range] { width: 100%; margin-top: .25rem; accent-color: var(--hd-accent); }
.macro { border: 2px dashed var(--hd-accent); padding: .7rem .8rem; border-radius: 8px; margin-bottom: 1rem; background: rgba(200,69,47,.06); }
.macro label { color: var(--hd-accent); }
.wrap { padding-right: 320px; }
@media (max-width: 820px) {
  .panel { position: static; width: auto; height: auto; border-left: none; border-bottom: 2px solid var(--hd-ink); }
  .wrap { padding-right: 1.25rem; }
}
.btn { font: inherit; border: 1px solid var(--hd-ink); background: var(--hd-paper); padding: .4rem .8rem; cursor: pointer; }
.rmnote { font-size: .78rem; opacity: .7; border-top: 1px dashed var(--hd-ink); padding-top: .7rem; margin-top: 1rem; }

/* panel section dividers */
.panel-section { border-top: 1px solid rgba(0,0,0,.12); padding-top: .8rem; margin-top: .8rem; }
.panel-section:first-of-type { border-top: none; margin-top: 0; }
.panel-section h4 { font-size: .88rem; margin: 0 0 .4rem; opacity: .6; text-transform: uppercase; letter-spacing: .05em; }
.btn-group { display: flex; flex-wrap: wrap; gap: .4rem; margin: .5rem 0; }
.btn-sm { font: inherit; font-size: .78rem; border: 1px solid var(--hd-ink); background: var(--hd-paper); padding: .25rem .55rem; cursor: pointer; }
.btn-sm:hover { background: var(--hd-ink); color: var(--hd-paper); }
.btn-sm.active { background: var(--hd-accent); color: var(--hd-paper); border-color: var(--hd-accent); }
select.demo-select { font: inherit; font-size: .82rem; padding: .3rem .5rem; border: 1px solid var(--hd-ink); background: var(--hd-paper); width: 100%; margin: .3rem 0 .6rem; }

/* module section separators in the main content area */
.module-sep { border: none; border-top: 3px dashed var(--hd-ink); margin: 4rem 0 3rem; opacity: .25; }

/* glitch demo */
.glitch-card { background: #111; color: #0f0; font-family: monospace; padding: 2rem; position: relative; min-height: 180px; overflow: hidden; }
.glitch-heading { font-size: 2rem; font-weight: 800; letter-spacing: .04em; }
.glitch-photo-placeholder { width: 100%; height: 160px; background: linear-gradient(135deg, #1a1a2e, #16213e, #0f3460, #533483); display: flex; align-items: center; justify-content: center; color: rgba(255,255,255,.4); font-size: .85rem; }

/* text-motion demo */
.tm-demo-text { font-size: clamp(1.6rem, 4vw, 2.8rem); font-weight: 700; line-height: 1.3; margin: 1rem 0; }
.tm-sample { font-size: 1.15rem; margin: .6rem 0; }

/* media-decay demo */
.md-photo-placeholder { width: 100%; height: 200px; position: relative; overflow: hidden; }
.md-photo-placeholder svg { width: 100%; height: 100%; }
.md-text-block { padding: 1.5rem; background: #f5f0e6; }
"""

# ---- Hand-drawn dials ----------------------------------------------------- #
HD_DIALS = [
    ("Wobble", "--hd-wobble", 0, 100, 55),
    ("Grain", "--hd-grain", 0, 100, 60),
    ("Rotation (scatter)", "--hd-rotation", 0, 100, 45),
    ("Boil speed", "--hd-boil-speed", 0, 100, 50),
    ("Sketchiness", "--hd-sketchiness", 0, 100, 50),
    ("Line weight", "--hd-line-weight", 0, 100, 50),
    ("Overshoot", "--hd-overshoot", 0, 100, 45),
]

# ---- Glitch dials --------------------------------------------------------- #
GL_DIALS = [
    ("RGB Split", "--gl-rgb-split", 0, 100, 0),
    ("Jitter", "--gl-jitter", 0, 100, 0),
    ("Dropout", "--gl-dropout", 0, 100, 0),
    ("Block Shift", "--gl-block-shift", 0, 100, 0),
    ("Scanlines", "--gl-scanlines", 0, 100, 0),
    ("Static", "--gl-static", 0, 100, 0),
    ("Rate", "--gl-rate", 0, 100, 0),
]

# ---- Text-motion dials ---------------------------------------------------- #
TM_DIALS = [
    ("Speed", "--tm-speed", 0, 100, 50),
    ("Stagger", "--tm-stagger", 0, 100, 45),
    ("Randomness", "--tm-randomness", 0, 100, 0),
    ("Scramble Pool", "--tm-scramble-pool", 0, 100, 30),
    ("Overshoot", "--tm-overshoot", 0, 100, 40),
]

# ---- Media-decay dials ---------------------------------------------------- #
MD_DIALS = [
    ("Grain", "--md-grain", 0, 100, 0),
    ("Dust", "--md-dust", 0, 100, 0),
    ("Warble", "--md-warble", 0, 100, 0),
    ("Ghosting", "--md-ghosting", 0, 100, 0),
    ("Tint", "--md-tint", 0, 100, 0),
    ("Vignette", "--md-vignette", 0, 100, 0),
    ("Flutter", "--md-flutter", 0, 100, 0),
]


def dial_html(label, var, lo, hi, val):
    sid = "s" + var.replace("--", "").replace("-", "_")   # e.g. shd_wobble
    return (
        f'<div class="dial"><label for="{sid}">{label}<output id="out{var}" for="{sid}">{val}</output></label>'
        f'<input id="{sid}" type="range" min="{lo}" max="{hi}" value="{val}" '
        f'aria-label="{label}" oninput="setDial(\'{var}\', this.value)"></div>'
    )


hd_dials_markup = "\n".join(dial_html(*d) for d in HD_DIALS)
gl_dials_markup = "\n".join(dial_html(*d) for d in GL_DIALS)
tm_dials_markup = "\n".join(dial_html(*d) for d in TM_DIALS)
md_dials_markup = "\n".join(dial_html(*d) for d in MD_DIALS)

PANEL = f"""
<aside class="panel" aria-label="Style Engine control panel">
  <h3>Style Engine · dials</h3>
  <p class="sub">Every slider writes a namespaced CSS variable 0-100. The panel is the seed of the future macro UI.</p>

  <div class="macro">
    <div class="dial"><label for="smacro">MACRO · Hand-Made-ness<output id="outmacro" for="smacro">50</output></label>
    <input id="smacro" type="range" min="0" max="100" value="50" aria-label="Macro: Hand-Made-ness" oninput="setMacro(this.value)"></div>
    <p class="sub" style="margin:0">One dial drives many params (wobble, rotation, sketchiness, boil, grain), exactly like an Ableton rack macro.</p>
  </div>

  <div class="panel-section">
    <h4>Hand-Drawn <code>--hd-*</code></h4>
    {hd_dials_markup}
  </div>

  <div class="panel-section">
    <h4>Glitch <code>--gl-*</code></h4>
    {gl_dials_markup}
    <button class="btn-sm" onclick="StyleEngine.glitch.burst(document.querySelector('.gl-target'), 500)">Burst!</button>
  </div>

  <div class="panel-section">
    <h4>Text-Motion <code>--tm-*</code></h4>
    {tm_dials_markup}
    <div style="margin:.4rem 0">
      <label for="tmRevealType" style="font-size:.82rem;font-weight:600">Reveal type</label>
      <select id="tmRevealType" class="demo-select" onchange="switchRevealType(this.value)">
        <option value="staggered-rise">staggered-rise</option>
        <option value="cascade-drop">cascade-drop</option>
        <option value="typewriter">typewriter</option>
        <option value="scramble">scramble</option>
        <option value="blur-in">blur-in</option>
        <option value="wipe">wipe</option>
      </select>
    </div>
    <button class="btn-sm" onclick="replayTextMotion()">Replay</button>
  </div>

  <div class="panel-section">
    <h4>Media-Decay <code>--md-*</code></h4>
    {md_dials_markup}
    <div class="btn-group">
      <button class="btn-sm" onclick="applyMdPreset('VINYL')">VINYL</button>
      <button class="btn-sm" onclick="applyMdPreset('VHS')">VHS</button>
      <button class="btn-sm" onclick="applyMdPreset('CASSETTE')">CASSETTE</button>
      <button class="btn-sm" onclick="applyMdPreset('CLEAN')">CLEAN</button>
    </div>
  </div>

  <div class="panel-section">
    <h4>Macro Engine</h4>
    <div class="macro">
      <div class="dial"><label for="sdecay">DECAY (cross-module)<output id="outdecay" for="sdecay">0</output></label>
      <input id="sdecay" type="range" min="0" max="100" value="0" aria-label="Macro: DECAY" oninput="setDecayMacro(this.value)"></div>
      <p class="sub" style="margin:0">Drives grain, tint, warble, ghosting, and glitch dropout across media-decay + glitch from one knob.</p>
    </div>
  </div>

  <p class="rmnote" id="rmnote">Motion respects <code>prefers-reduced-motion</code>. Toggle it in your OS to see boil, glitch stepping, and text reveals freeze.</p>
</aside>
"""

# --------------------------- demo body sections --------------------------- #
BODY = f"""
{PANEL}
<div class="wrap">
  <header>
    <h1 class="title hd-hand">The Hand-Drawn Module</h1>
    <p class="tagline hd-body">Style Engine · Module 1. Every effect below is driven by a
    <strong>0-100 dial</strong> (<code>--hd-*</code>). Drag the sliders on the right — nothing here
    is hard-coded. A future macro layer will drive all of these dials at once.</p>
  </header>

  <section class="demo" id="s-wobble">
    <span class="demo__label">01 · wobbly containers</span>
    <h2 class="hd-body">border-radius that breathes</h2>
    <p class="demo__note">Each box interpolates 8 seeded radii toward the classic
    <code>255px 15px 225px 15px / 15px 225px 15px 255px</code> by the Wobble dial. No two identical.</p>
    <div class="grid">
      <div class="hd-box hd-body"><strong>Ticket #1</strong><br>A wobbly ink container.</div>
      <div class="hd-box hd-body" style="--hdr1:180;--hdr2:30;--hdr3:255;--hdr4:22;--hdr5:40;--hdr6:200;--hdr7:26;--hdr8:210;"><strong>Ticket #2</strong><br>Different seed set.</div>
      <div class="hd-box hd-body" style="--hdr1:60;--hdr2:200;--hdr3:90;--hdr4:175;--hdr5:210;--hdr6:55;--hdr7:190;--hdr8:70;"><strong>Ticket #3</strong><br>Different again.</div>
      <div class="hd-box hd-body"><strong>Ticket #4</strong><br>nth-of-type varies it.</div>
    </div>
  </section>

  <section class="demo" id="s-scatter">
    <span class="demo__label">02 · scatter</span>
    <h2 class="hd-body">prime-cadence rotation (3n / 5n / 7n)</h2>
    <p class="demo__note">Rotations step on primes so they never land on a grid; magnitude +-2-5 deg from the Rotation dial.</p>
    <div class="grid hd-scatter">
      {''.join(f'<div class="chip hd-body">tag {i+1}</div>' for i in range(12))}
    </div>
  </section>

  <section class="demo" id="s-roughen">
    <span class="demo__label">03 · roughen filter</span>
    <h2 class="hd-body">feTurbulence + feDisplacementMap</h2>
    <p class="demo__note">Displacement <code>scale</code> is an SVG attribute CSS can't set — the JS binder writes it from the Sketchiness dial.</p>
    <div class="grid">
      <div class="sample-fill hd-roughen">roughened block — edges displaced</div>
      <div class="hd-box hd-roughen hd-body">roughen on a wobbly box, stacked</div>
    </div>
  </section>

  <section class="demo" id="s-boil">
    <span class="demo__label">04 · boil animation</span>
    <h2 class="hd-body">discrete baseFrequency stepping</h2>
    <p class="demo__note"><code>calcMode="discrete"</code> is mandatory — it jumps between frames like redrawing by hand. Boil-speed dial writes <code>dur</code>. Frozen under reduced-motion.</p>
    <div class="grid">
      <div class="sample-fill hd-boil">boiling block</div>
      <h2 class="hd-hand hd-boil" style="font-size:2.4rem;color:var(--hd-accent2)">Boiling headline</h2>
    </div>
  </section>

  <section class="demo" id="s-grain">
    <span class="demo__label">05 · grain</span>
    <h2 class="hd-body">fractalNoise paper overlay</h2>
    <p class="demo__note">A fixed full-page grain overlay at 5-15% opacity (Grain dial), multiply-blended over cream paper. Turn Grain up to see it bite.</p>
    <div class="sample-fill hd-body" style="color:var(--hd-paper)">The grain sits above everything as a multiply overlay. Raise the Grain dial.</div>
  </section>

  <section class="demo" id="s-draw">
    <span class="demo__label">06 · self-drawing lines</span>
    <h2 class="hd-body">stroke-dashoffset + getTotalLength()</h2>
    <p class="demo__note">Path length measured with <code>getTotalLength()</code>; the line draws itself. Duration from the Boil-speed dial. Instant under reduced-motion.</p>
    <svg viewBox="0 0 600 120" width="100%" height="120" aria-hidden="true">
      <path class="hd-draw-path" d="M10,90 C120,10 220,140 320,60 S520,10 590,80"/>
    </svg>
    <button class="btn" onclick="StyleEngine.drawLines('.hd-draw-path')">replay draw</button>
  </section>

  <section class="demo" id="s-rough">
    <span class="demo__label">07 · Rough.js shapes</span>
    <h2 class="hd-body">seeded sketchy shapes</h2>
    <p class="demo__note">Rough.js with <code>roughness</code> from the Sketchiness dial, <code>bowing</code>, and a STABLE-per-element seed (stable on reflow, different between shapes). Re-render on dial change.</p>
    <canvas id="roughcanvas" width="1000" height="260"></canvas>
  </section>

  <section class="demo" id="s-note">
    <span class="demo__label">08 · rough-notation</span>
    <h2 class="hd-body">annotations, used <span id="note-underline">sparingly</span></h2>
    <p class="demo__note hd-body">Reserve 3-5 per page for the words that matter most: a
    <span id="note-circle">deadline</span>, a <span id="note-highlight">key number</span>, a
    <span id="note-box">warning</span>. Over-use and the eye stops trusting them.</p>
    <button class="btn" onclick="runNotations()">replay annotations</button>
  </section>

  <section class="demo" id="s-riso">
    <span class="demo__label">09 · risograph poster (composed)</span>
    <h2 class="hd-body">flat inks · multiply · misregistration · halftone</h2>
    <p class="demo__note">2-3 flat inks, each on a multiply layer, offset 1-3px (Sketchiness dial) so overlaps mix and edges misregister. Halftone dot grid underneath.</p>
    <div class="hd-riso" style="position:relative;height:420px;border:1px solid var(--hd-ink);overflow:hidden;background:var(--hd-paper)">
      <div class="hd-halftone" style="position:absolute;inset:0;opacity:.25"></div>
      <div class="hd-riso__layer hd-riso__layer--yellow" style="display:flex;align-items:center;justify-content:center">
        <div style="font:800 clamp(3rem,12vw,7rem)/0.9 'Caveat',cursive;text-align:center">NIGHT<br>PRESS</div>
      </div>
      <div class="hd-riso__layer hd-riso__layer--blue" style="display:flex;align-items:center;justify-content:center">
        <div style="font:800 clamp(3rem,12vw,7rem)/0.9 'Caveat',cursive;text-align:center">NIGHT<br>PRESS</div>
      </div>
      <div class="hd-riso__layer hd-riso__layer--red" style="display:flex;align-items:flex-end;justify-content:center;padding-bottom:1.5rem">
        <div class="hd-body" style="font-weight:700;letter-spacing:.3em">RISO ZINE FAIR — SAT 8PM</div>
      </div>
    </div>
  </section>

  <footer class="hd-body" style="opacity:.6;font-size:.85rem;border-top:1px dashed var(--hd-ink);padding-top:1rem">
    Style Engine · Module 1 · Hand-Drawn. Built to prove the dial architecture. Next modules
    (glitch <code>--gl-*</code>, text-motion <code>--tm-*</code>, media-decay <code>--md-*</code>) reuse the same 0-100 convention.
  </footer>

  <!-- ================================================================== -->
  <!--  MODULE 2: GLITCH                                                   -->
  <!-- ================================================================== -->
  <hr class="module-sep">
  <header>
    <h1 class="title" style="font-family:monospace;color:#0f0;text-shadow:2px 0 #f00,-2px 0 #0ff">The Glitch Module</h1>
    <p class="tagline hd-body">Style Engine · Module 2. Digital breakage driven by seven
    <code>--gl-*</code> dials. RGB splits, jitter, dropouts, block shifts, scanlines, static noise,
    and a rate clock. Everything is stepped (no smooth easing) — true digital corruption.</p>
  </header>

  <section class="demo" id="s-glitch-composite">
    <span class="demo__label">10 · composite glitch target</span>
    <h2 class="hd-body">all seven effects at once</h2>
    <p class="demo__note">The <code>.gl-target</code> class applies every glitch effect: RGB split, jitter, dropout,
    block shift, scanlines, and static noise. Turn up the Rate dial first, then adjust the others.</p>
    <div class="grid" style="grid-template-columns:1fr 1fr">
      <div>
        <h3 class="glitch-heading gl-target" data-gl-text="SIGNAL LOST" style="margin:0 0 .5rem">SIGNAL LOST</h3>
        <div class="glitch-photo-placeholder gl-target">
          <svg viewBox="0 0 200 120" width="200" height="120" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <rect width="200" height="120" fill="none"/>
            <circle cx="60" cy="50" r="20" fill="rgba(255,255,255,.15)"/>
            <polygon points="20,110 80,40 140,80 200,30 200,120 0,120" fill="rgba(255,255,255,.1)"/>
          </svg>
        </div>
      </div>
      <div class="glitch-card gl-target" id="glitch-card">
        <div style="font-size:1.4rem;font-weight:700;margin-bottom:.5rem">// CORRUPTED BLOCK</div>
        <div style="opacity:.7">error: unexpected token at position 0x3F2A</div>
        <div style="opacity:.5;margin-top:.5rem">stack trace truncated...</div>
        <div style="margin-top:1rem">
          <button class="btn" style="color:#0f0;border-color:#0f0" onclick="StyleEngine.glitch.burst(this.closest('.gl-target'), 500)">Burst!</button>
        </div>
      </div>
    </div>
    <p class="demo__note" style="margin-top:1rem">The <strong>Burst!</strong> button calls
    <code>StyleEngine.glitch.burst(el, 500)</code> — it maxes every glitch dial on that element for 500ms,
    then restores the prior state.</p>
  </section>

  <!-- ================================================================== -->
  <!--  MODULE 3: TEXT-MOTION                                              -->
  <!-- ================================================================== -->
  <hr class="module-sep">
  <header>
    <h1 class="title hd-hand">The Text-Motion Module</h1>
    <p class="tagline hd-body">Style Engine · Module 3. Six composable text reveals:
    typewriter, scramble, staggered-rise, wipe, cascade-drop, and blur-in. Each is driven by
    five <code>--tm-*</code> dials. Switch the reveal type in the panel and hit Replay.</p>
  </header>

  <section class="demo" id="s-text-motion">
    <span class="demo__label">11 · text reveals</span>
    <h2 class="hd-body">per-character animation from dials</h2>
    <p class="demo__note">Each line below uses a different reveal type. Change the reveal type dropdown in the panel
    to switch all lines at once, then click Replay to re-trigger them.</p>

    <div class="tm-demo-text tm-target" data-tm="staggered-rise" id="tm-line-1">Every letter earns its place on the page.</div>
    <div class="tm-sample tm-target" data-tm="scramble" id="tm-line-2">The scramble locks in one character at a time, slot-machine style.</div>
    <div class="tm-sample tm-target" data-tm="typewriter" id="tm-line-3">Typewriter reveals with a blinking cursor trailing behind.</div>
    <div class="tm-sample tm-target" data-tm="blur-in" id="tm-line-4">Blur-in fades from soft focus to sharp, letter by letter.</div>
    <div class="tm-sample tm-target" data-tm="cascade-drop" id="tm-line-5">Cascade-drop: letters fall into position from above.</div>
    <div class="tm-sample tm-target" data-tm="wipe" id="tm-line-6">Wipe reveals the entire line via clip-path.</div>

    <div style="margin-top:1rem">
      <button class="btn" onclick="replayTextMotion()">Replay</button>
    </div>
  </section>

  <!-- ================================================================== -->
  <!--  MODULE 4: MEDIA-DECAY                                             -->
  <!-- ================================================================== -->
  <hr class="module-sep">
  <header>
    <h1 class="title hd-hand">The Media-Decay Module</h1>
    <p class="tagline hd-body">Style Engine · Module 4. Analog wear and degradation: film grain,
    dust and scratches, tape warble, soft chroma ghosting, sun-faded tint, vignette darkening,
    and projector flutter. Seven <code>--md-*</code> dials, plus named presets (VINYL, VHS, CASSETTE).</p>
  </header>

  <section class="demo" id="s-media-decay">
    <span class="demo__label">12 · analog decay</span>
    <h2 class="hd-body">progressive physical media wear</h2>
    <p class="demo__note">The <code>.md-target</code> class applies all decay effects at once.
    Try the preset buttons in the panel, or dial each effect individually.</p>

    <div class="grid" style="grid-template-columns:1fr 1fr">
      <div class="md-target md-photo-placeholder" id="md-photo">
        <svg viewBox="0 0 400 200" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" aria-hidden="true">
          <defs>
            <linearGradient id="md-sky" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stop-color="#87CEEB"/>
              <stop offset="60%" stop-color="#E0B0FF"/>
              <stop offset="100%" stop-color="#FFD700"/>
            </linearGradient>
          </defs>
          <rect width="400" height="200" fill="url(#md-sky)"/>
          <circle cx="320" cy="60" r="30" fill="#FFD700" opacity=".8"/>
          <rect x="0" y="140" width="400" height="60" fill="#2d5016"/>
          <rect x="60" y="100" width="40" height="40" fill="#8B4513"/>
          <polygon points="60,100 80,70 100,100" fill="#556B2F"/>
          <rect x="250" y="110" width="50" height="30" fill="#8B4513"/>
          <polygon points="250,110 275,85 300,110" fill="#556B2F"/>
        </svg>
      </div>
      <div class="md-target md-text-block" id="md-text">
        <h3 style="margin:0 0 .5rem">Faded Memories</h3>
        <p style="margin:0;opacity:.85;font-size:.92rem">This text block degrades alongside the photo.
        Film grain, dust specks, and warm tint build up as you raise the dials.
        The ghosting effect duplicates the content as a soft, blurred, color-shifted layer behind it.</p>
      </div>
    </div>

    <div style="margin-top:1rem" class="btn-group">
      <button class="btn" onclick="applyMdPreset('VINYL')">VINYL</button>
      <button class="btn" onclick="applyMdPreset('VHS')">VHS</button>
      <button class="btn" onclick="applyMdPreset('CASSETTE')">CASSETTE</button>
      <button class="btn" onclick="applyMdPreset('CLEAN')">CLEAN</button>
    </div>
  </section>

  <!-- ================================================================== -->
  <!--  THE MACRO ENGINE                                                   -->
  <!-- ================================================================== -->
  <hr class="module-sep">
  <header>
    <h1 class="title hd-hand">The Macro Engine</h1>
    <p class="tagline hd-body">Style Engine · Routing Layer. A macro is one 0-100 knob that drives
    many module dials at once — each with its own range, curve, and active window. Exactly like an
    Ableton Live effect-rack macro knob. The DECAY macro below drives dials across media-decay
    <em>and</em> glitch from a single slider.</p>
  </header>

  <section class="demo" id="s-macro">
    <span class="demo__label">13 · the DECAY macro</span>
    <h2 class="hd-body">one knob, progressive cross-module rot</h2>
    <p class="demo__note">DECAY is a starter preset that ships with the macro engine. At low values
    grain and tint creep in (media-decay). Mid-range brings warble. Past 50 ghosting fades in exponentially.
    Above 70, glitch dropouts kick in. All from one slider.</p>

    <div class="macro" style="max-width:500px">
      <div class="dial"><label for="sdecay2">DECAY<output id="outdecay2" for="sdecay2">0</output></label>
      <input id="sdecay2" type="range" min="0" max="100" value="0" aria-label="Macro: DECAY" oninput="setDecayMacro(this.value)"></div>
    </div>

    <p class="demo__note">The macro engine also supports <code>serialize()</code> / <code>load()</code>
    for full preset snapshots (every dial across every module + every macro definition, as a versioned JSON object).
    This is the <code>styleEnginePreset v1</code> format — save and restore your entire effect state.</p>
  </section>

  <footer class="hd-body" style="opacity:.6;font-size:.85rem;border-top:1px dashed var(--hd-ink);padding-top:1rem;margin-top:3rem">
    Style Engine · four modules (hand-drawn, glitch, text-motion, media-decay) + macro engine.
    Every effect is a 0-100 dial. Every module speaks the same <code>StyleEngine.setDial()</code> API.
    One macro can drive dials across all of them.
  </footer>
</div>
"""

# --------------------------- demo-only JS --------------------------- #
DEMO_JS = r"""
// setDial proxies to the module's public API and updates the readout.
function setDial(name, value) {
  StyleEngine.setDial(name, value);
  var out = document.getElementById('out' + name);
  if (out) out.textContent = value;
  renderRough();
}

// MACRO: one 0-100 input mapped onto many dials (the future macro layer, in miniature).
// Each mapping is (dialVar, curveFn) so a macro can be non-linear per target.
var MACRO_MAP = [
  ['--hd-wobble',      function (m) { return Math.round(m); }],
  ['--hd-rotation',    function (m) { return Math.round(m * 0.9); }],
  ['--hd-sketchiness', function (m) { return Math.round(m); }],
  ['--hd-boil-speed',  function (m) { return Math.round(m * 0.8); }],
  ['--hd-grain',       function (m) { return Math.round(m * 0.28); }],
  ['--hd-line-weight', function (m) { return Math.round(m); }],
  ['--hd-overshoot',   function (m) { return Math.round(m); }]
];
function setMacro(m) {
  m = parseFloat(m);
  document.getElementById('outmacro').textContent = Math.round(m);
  MACRO_MAP.forEach(function (pair) {
    var v = pair[1](m);
    StyleEngine.setDial(pair[0], v);
    // reflect on the individual slider + readout so users SEE one dial move many
    var slider = document.querySelector('input[oninput*="' + pair[0] + '"]');
    if (slider) slider.value = v;
    var out = document.getElementById('out' + pair[0]);
    if (out) out.textContent = v;
  });
  renderRough();
}

// Rough.js: seeded shapes, roughness from the sketchiness dial. Seeds are
// STABLE per shape (index-based) so shapes don't twitch, but DIFFER between shapes.
function renderRough() {
  var cv = document.getElementById('roughcanvas');
  if (!cv || typeof rough === 'undefined') return;
  var ctx = cv.getContext('2d');
  ctx.clearRect(0, 0, cv.width, cv.height);
  var rc = rough.canvas(cv);
  var sketch = parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--hd-sketchiness')) || 0;
  var roughness = 1 + (sketch / 100) * 1.8;   // dial 0-100 -> roughness 1.0-2.8
  var bowing = 0.5 + (sketch / 100) * 2;
  var ink = getComputedStyle(document.documentElement).getPropertyValue('--hd-ink').trim();
  var red = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent').trim();
  var blue = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent2').trim();
  var opt = function (i, stroke, fill) {
    return { roughness: roughness, bowing: bowing, seed: 1000 + i * 137,
             stroke: stroke, strokeWidth: 2, fill: fill, fillStyle: 'hachure', fillWeight: 1.5, hachureGap: 6 };
  };
  rc.rectangle(30, 30, 200, 190, opt(1, ink, red));
  rc.circle(360, 130, 180, opt(2, ink, blue));
  rc.ellipse(620, 130, 240, 150, opt(3, red, null));
  rc.line(770, 30, 970, 220, opt(4, blue));
  rc.path('M780,210 C820,120 900,120 950,40', opt(5, ink, null));
}

// rough-notation: 3-5 annotations MAX. Skip animation under reduced motion.
var _annotations = [];
function runNotations() {
  if (typeof RoughNotation === 'undefined') return;
  var reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  var red = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent').trim();
  var blue = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent2').trim();
  var yellow = getComputedStyle(document.documentElement).getPropertyValue('--hd-accent3').trim();
  _annotations.forEach(function (a) { a.hide(); });
  var dur = reduce ? 0 : 800;
  _annotations = [
    RoughNotation.annotate(document.getElementById('note-underline'), { type: 'underline', color: red, animationDuration: dur }),
    RoughNotation.annotate(document.getElementById('note-circle'), { type: 'circle', color: blue, padding: 6, animationDuration: dur }),
    RoughNotation.annotate(document.getElementById('note-highlight'), { type: 'highlight', color: yellow, animationDuration: dur }),
    RoughNotation.annotate(document.getElementById('note-box'), { type: 'box', color: red, animationDuration: dur })
  ];
  var group = RoughNotation.annotationGroup(_annotations);
  group.show();
}

// ---- Text-Motion controls ------------------------------------------------ //
function switchRevealType(type) {
  var lines = document.querySelectorAll('#s-text-motion .tm-target');
  for (var i = 0; i < lines.length; i++) {
    lines[i].setAttribute('data-tm', type);
  }
  replayTextMotion();
}

function replayTextMotion() {
  var lines = document.querySelectorAll('#s-text-motion .tm-target');
  for (var i = 0; i < lines.length; i++) {
    var type = lines[i].getAttribute('data-tm') || 'staggered-rise';
    StyleEngine.text.reveal(lines[i], type);
  }
}

// ---- Media-Decay preset buttons ------------------------------------------ //
function applyMdPreset(name) {
  StyleEngine.mediaDecay.applyPreset(name);
  // Reflect the preset's dial values back onto the panel sliders + readouts.
  var preset = StyleEngine.mediaDecay.presets[name];
  if (!preset) return;
  var dialNames = ['grain', 'dust', 'warble', 'ghosting', 'tint', 'vignette', 'flutter'];
  dialNames.forEach(function (d) {
    var v = preset[d];
    var cssVar = '--md-' + d;
    var slider = document.querySelector('input[oninput*="' + cssVar + '"]');
    if (slider) slider.value = v;
    var out = document.getElementById('out' + cssVar);
    if (out) out.textContent = v;
  });
}

// ---- DECAY macro (uses the macro engine) --------------------------------- //
var _decayLoaded = false;
function setDecayMacro(v) {
  v = parseFloat(v);
  // Update both readouts (panel + inline)
  var o1 = document.getElementById('outdecay');
  var o2 = document.getElementById('outdecay2');
  if (o1) o1.textContent = Math.round(v);
  if (o2) o2.textContent = Math.round(v);
  // Sync both sliders
  var s1 = document.getElementById('sdecay');
  var s2 = document.getElementById('sdecay2');
  if (s1) s1.value = v;
  if (s2) s2.value = v;

  if (!_decayLoaded && StyleEngine.macro && StyleEngine.macro.starterPresets) {
    // Load the DECAY starter preset (creates the macro definition).
    StyleEngine.macro.load(StyleEngine.macro.starterPresets.DECAY);
    _decayLoaded = true;
  }
  if (StyleEngine.macro) {
    StyleEngine.macro.setValue('decay-master', v);
  }
  // Reflect driven dials back to their panel sliders.
  reflectAllSliders();
}

// After a macro drives dials, update every slider and readout in the panel to match.
function reflectAllSliders() {
  var cs = getComputedStyle(document.documentElement);
  var allInputs = document.querySelectorAll('.panel input[type=range][oninput*="setDial"]');
  for (var i = 0; i < allInputs.length; i++) {
    var input = allInputs[i];
    var match = input.getAttribute('oninput').match(/setDial\('([^']+)'/);
    if (!match) continue;
    var cssVar = match[1];
    var rawVal = cs.getPropertyValue(cssVar);
    var numVal = parseFloat(rawVal);
    if (isNaN(numVal)) continue;
    numVal = Math.round(numVal);
    input.value = numVal;
    var out = document.getElementById('out' + cssVar);
    if (out) out.textContent = numVal;
  }
}

document.addEventListener('DOMContentLoaded', function () {
  renderRough();
  runNotations();
});
"""

HTML = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Style Engine — live demo (all modules)</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%23faf6ef'/%3E%3Cpath d='M15,70 C35,20 65,90 88,30' stroke='%231a1a17' stroke-width='9' fill='none' stroke-linecap='round'/%3E%3C/svg%3E">
<style>
/* ===== VENDORED FONTS (offline, no CDN) ===== */
{FONT_FACE_CSS}
/* ===== CANONICAL MODULE CSS (inlined verbatim from modules/) ===== */
/* -- hand-drawn.css -- */
{hd_css}
/* -- glitch.css -- */
{gl_css}
/* -- text-motion.css -- */
{tm_css}
/* -- media-decay.css -- */
{md_css}
/* ===== demo chrome ===== */
{DEMO_CSS}
</style>
</head>
<body class="hd-page hd-body">
<!-- ===== CANONICAL SVG FILTER DEFS (inlined from modules/) ===== -->
{hd_svg}
{gl_svg}
{md_svg}
<!-- full-page grain overlay -->
<svg class="hd-grain-overlay" aria-hidden="true"><rect width="100%" height="100%" filter="url(#hd-grain)"/></svg>

{BODY}

<!-- ===== vendored libraries (inlined) ===== -->
<script>/* Rough.js v4.6.6 (MIT) */ {rough_js}</script>
<script>/* rough-notation v0.2.1 (MIT) */ {roughnote_js}</script>
<!-- ===== CANONICAL MODULE BINDERS (inlined verbatim from modules/) ===== -->
<!-- hand-drawn.js creates the StyleEngine registry; load it FIRST -->
<script>{hd_js}</script>
<script>{gl_js}</script>
<script>{tm_js}</script>
<script>{md_js}</script>
<!-- macro.js must load LAST (after all modules register) -->
<script>{macro_js}</script>
<!-- ===== demo controls ===== -->
<script>{DEMO_JS}</script>
</body>
</html>
"""

OUT.write_text(HTML, encoding="utf-8")
print(f"wrote {OUT} ({len(HTML):,} bytes)")
